### ISSUE TITLE
Relationship with other codebases and frameworks

### ISSUE THREAD

**Issue by sgbaird** [darkreactions/ESCALATE#234]
Nice repository! Had the pleasure of meeting Joshua Schrier at the recent TMS meeting and came across a Twitter post by him about ESCALATE. Curious if you could help me put this repository in the context of a few other repositories/methodologies.

- [Citrine's GEMD format](https://citrineinformatics.github.io/gemd-docs/)
- [RO-Crate](https://github.com/ResearchObject/ro-crate)
- [Chemios](https://github.com/Chemios/chemios)
- [HELAO](https://github.com/helgestein/helao-pub)
- Toyota Research Institute's [CAMD](https://github.com/TRI-AMDD/CAMD), ACE, and BEEP (https://doi.org/10.1063/5.0076324)
- [Laboratory Management Systems](https://en.wikipedia.org/wiki/Laboratory_information_management_system) (LMS) or Electronic Laboratory Notebooks (ELNs) such as [SciNote](https://www.scinote.net/) (maybe also [LabCollector](https://labcollector.com/solutions/technology/labcollector-api/) which I have less familiarity with but seems to have a data API for interfacing hardware - so maybe more relevant)
- https://protocols.io

If you know of any other codebases/software/systems related to the topic, would love to hear about them. I've been keeping a list at https://github.com/stars/sgbaird/lists/lab-automation.

**Comment by jschrier** [comment]
We're in the process of trying to write a manuscript on this...which will include some of that context.  Some other things we are aware of include

Alexei Lapkin’s stuff [recent paper/perspective https://pubs.acs.org/doi/10.1021/jacsau.1c00438 ... This might be a good place to introduce everything and we might defer detailed discussion to this review]

- Cronin’s XDL/Chemputer — somewhat different goals, but some relationship
- Autoprotocol—again, attempt at descriptive language, rather than full stack 
- ESAMP [Toyota research + John Gregoire]
- Aquarium [SD2 performer @ University of Washington]
- EPFL project (Jablonka, Smit)
- Open Reaction Database [cite: 10.1021/jacs.1c09820]
- MIT Polymer database [find cite from AIChE 2021 notes]
- AirChem 
- ChemMotion ELN https://depth-first.com/articles/2022/02/23/big-reaction-data/ —more of an ELN with some data features
