### ISSUE TITLE
[BUG] API POST does not return identifier of new resource

### ISSUE THREAD

**Issue by miketynes** [darkreactions/ESCALATE#37]
(I'm not sure if this quite falls under [BUG], but I think its a problem that needs fixing)

**To reproduce**
Log in and navigate to the browsable rest api endpoint for person. 
Fill out the post form for a new person. 

**Expected behavior**
The response body should contain the uuid of the new resource, but does not

**Screenshots**
Observe this example -- the url (which should contain the uid) is `null`. 
![image](https://user-images.githubusercontent.com/25695528/91109972-8ade1500-e64a-11ea-879e-1464e9b5bc95.png)

**Additional context**
I suspect this has to do with the creation of UUIDs by Postgres and not by Django, and that Django doesn't know it has to run the Postgres upsert function before returning a reference to the new resource.

**Comment by gcatabr1** [comment]
From Postgres, this is by design. What gets returned is the Person's associated Actor uuid (and record). The thought is that the Actor record is used in subsequent entities and not the Person. 
Sequence of events -> Person, Organization or Systemtool record is created -> Actor record automatically created that points back to the associated Person, Org, Systemtool record via their uuid. In other words, the [person] upsert function does two inserts: first inserts the Person record, then inserts an associated Actor record. Same goes for Organization and Systemtool.

**Comment by vshekar** [comment]
This seems to be a Django side issue. You will get the pk if it is an integer but not if it is a UUID.

I hopped on the #django IRC channel yesterday and asked them about it. From what I understand some databases don't return the result of an insert (apparently it does in MySQL and SQLite). A work around this they suggested I use the [refresh_from_db()](https://docs.djangoproject.com/en/3.1/ref/models/instances/#refreshing-objects-from-database) function. But it does not work in our case, when the function is called it says that instance does not exist because there is a slight mismatch between the add_date and mod_date auto generated by Django and the one generated by Postgres. Trying to figure out how to avoid this.

**Comment by gcatabr1** [comment]
I've just pushed up a change to the org, person and systemtool views to ensure the created (inserted/POSTed) record uuid is returned.

**Comment by vshekar** [comment]
🎊 🎊 🎊 🎊 
For reference, in Postgres custom functions that are triggered `INSTEAD OF` `INSERT` or `UPDATE` do not automatically return the newly added row unless there is a `RETURNING` clause at the end of the statement. This seems to exist only in Postgres and Oracle DB. In Postgres it only exists for triggers not for regular tables. [Stack overflow question](https://stackoverflow.com/questions/7948794/postgresql-trigger-not-returning-anything)

On the other hand, Django ORM does not automatically add a `RETURNING` statement for Postgres (or any other database). So to add it,  one must create a custom model field that sets `db_returning = True` as done [in this commit](https://github.com/darkreactions/ESCALATE/pull/53/commits/d10313ac9b1d8aefb9c2210121480ba68c90ca5b)
